bde_event_viewevent:
    path:      /event/{id}
    defaults:
         _controller: BDEEventBundle:Event:viewEvent
    requirements:
        id: \d+

bde_event_index:
    path:      /events
    defaults:
         _controller: BDEEventBundle:Event:events

bde_event_viewsuggestion:
    path:      /suggestion/{id}
    defaults:
         _controller: BDEEventBundle:Event:viewSuggestion
    requirements:
        id: \d+

bde_event_suggestion:
    path:      /suggestion
    defaults:
         _controller: BDEEventBundle:Event:suggestion

bde_event_add:
    path:      /addevent
    defaults:
         _controller: BDEEventBundle:Event:addEvent

bde_event_addSuggestion:
    path:      /addsuggestion
    defaults:
         _controller: BDEEventBundle:Event:addSuggestion

bde_event_delete:
    path:      /event/delete/{id}
    defaults:
         _controller: BDEEventBundle:Event:deleteEvent
    requirements:
        id: \d+

bde_event_edit:
    path:      /event/edit/{id}
    defaults:
         _controller: BDEEventBundle:Event:editEvent
    requirements:
        id: \d+