bde_account_register:
    path:     /register/
    defaults:
        _controller: BDEAccountBundle:Account:register

bde_account_login:
    path:     /login
    defaults:
        _controller: BDEAccountBundle:Account:login

bde_account_disconnect:
    path:     /disconnect
    defaults:
        _controller: BDEAccountBundle:Account:disconnect

