bde_admin_index:
    path:     /admin
    defaults:
        _controller: BDEAdminBundle:Admin:Admin

bde_admin_viewsuggestion:
    path:     /admin/suggestion/{id}
    defaults:
         _controller: BDEAdminBundle:Admin:viewSuggestion
    requirements:
        id: \d+

bde_admin_viewuser:
    path:     /admin/user/{id}
    defaults:
         _controller: BDEAdminBundle:Admin:viewUser
    requirements:
        id: \d+