<?php

namespace BDE\ShopBundle\Repository;

/**
 * Articles_categorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Articles_categorieRepository extends \Doctrine\ORM\EntityRepository
{
}
