<?php

namespace BDE\ShopBundle\Repository;

/**
 * Orders_lineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Orders_lineRepository extends \Doctrine\ORM\EntityRepository
{
}
