<?php

namespace BDE\EventBundle\Repository;

/**
 * Events_picture_commentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Events_picture_commentRepository extends \Doctrine\ORM\EntityRepository
{
}
