<?php

namespace BDE\EventBundle\Repository;

/**
 * Events_pictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Events_pictureRepository extends \Doctrine\ORM\EntityRepository
{
}
