<?php

namespace BDE\EventBundle\Repository;

/**
 * RegisterEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegisterEventRepository extends \Doctrine\ORM\EntityRepository
{
}
